#!/usr/bin/env python3
"""
HTML Template Analysis Tool
===========================
Analyzes index.html structure for Jinja2 template splitting.

Usage: python scripts/analyze_html.py
"""

import re
from pathlib import Path


def analyze_html():
    """Analyze index.html and document template split boundaries."""

    html_path = Path("index.html")
    if not html_path.exists():
        print("ERROR: index.html not found in current directory")
        return

    content = html_path.read_text(encoding="utf-8")
    lines = content.split("\n")

    print("=" * 70)
    print("HTML STRUCTURE ANALYSIS REPORT")
    print("=" * 70)
    print()

    # ─── HEAD ELEMENTS ────────────────────────────────────────────────────────
    print("📋 <head> ELEMENTS (Lines 8-200)")
    print("-" * 70)
    head_lines = [(i+1, lines[i]) for i in range(7, 200) if lines[i].strip()]
    for ln, line in head_lines[:15]:
        print(f"  Line {ln}: {line.strip()}")
    print("  ... (inline <style> block at lines 13-199)")
    print()

    # ─── INLINE STYLE BLOCK ───────────────────────────────────────────────────
    print("🎨 INLINE <style> BLOCK (Lines 13-199)")
    print("-" * 70)
    print("  Location: <head>...</head> section")
    print("  Purpose: Editorial template customizations")
    print("  Contains: Sidebar styling, section borders, responsive breakpoints")
    print()

    # ─── SIDEBAR NAVIGATION ───────────────────────────────────────────────────
    print("🧭 SIDEBAR NAVIGATION (Lines 207-217)")
    print("-" * 70)
    print("  Structure: <div id='sidebar'> with <h2> + <nav>")
    print("  Links:")
    nav_lines = [(i+1, lines[i]) for i in range(208, 217) if '<a href=' in lines[i]]
    for ln, line in nav_lines:
        match = re.search(r'href="([^"]+)"[^>]*>([^<]+)</a>', line)
        if match:
            print(f"    Line {ln}: #{match.group(1)} → {match.group(2)}")
    print()

    # ─── STATIC SECTIONS ───────────────────────────────────────────────────────
    print("📦 STATIC SECTIONS (preserved in base.html)")
    print("-" * 70)

    static_sections = [
        ("#intro", "소개", 223, 242, "Introduction hero section with profile"),
        ("#first", "에이전트 헤르", 245, 270, "Agent Her capabilities"),
        ("#second", "사용자 정보", 273, 297, "User information"),
        ("#third", "메모리 시스템", 300, 324, "Memory system description"),
        ("#cta", "함께해볼까요?", 420, 429, "Call to action with GitHub link"),
        ("#spacer", "스페이서", 432, 432, "Empty spacer for footer spacing"),
    ]

    for sid, name, start, end, desc in static_sections:
        print(f"  [{sid}] {name}")
        print(f"    Lines {start}-{end} ({end-start+1} lines)")
        print(f"    {desc}")
        print()

    # ─── DYNAMIC SECTIONS ─────────────────────────────────────────────────────
    print("⚡ DYNAMIC SECTIONS (generated by Python)")
    print("-" * 70)

    dynamic_sections = [
        ("#fourth", "활동 타임라인", 327, 380,
         "Timeline entries - 9 activity blocks\n"
         "    → Sub-section: heatmap.html (contribution heatmap)\n"
         "    → Sub-section: stats.html (activity statistics)"),
        ("#fifth", "크론 작업", 383, 417,
         "Cron jobs listing - 6 registered jobs with status"),
    ]

    for sid, name, start, end, desc in dynamic_sections:
        print(f"  [{sid}] {name}")
        print(f"    Lines {start}-{end} ({end-start+1} lines)")
        print(f"    {desc}")
        print()

    # ─── JAVASCRIPT FILES ─────────────────────────────────────────────────────
    print("📜 <script> TAGS (Lines 445-451)")
    print("-" * 70)
    js_files = []
    for i, line in enumerate(lines):
        if "<script src=" in line:
            match = re.search(r'<script src="([^"]+)"', line)
            if match:
                js_files.append((i+1, match.group(1)))
    for ln, file in js_files:
        print(f"  Line {ln}: {file}")
    print(f"  Total: {len(js_files)} JavaScript files")
    print()

    # ─── TEMPLATE SPLIT PLAN ──────────────────────────────────────────────────
    print("📋 TEMPLATE SPLIT PLAN")
    print("=" * 70)
    print()
    print("base.html         - Full HTML shell with Jinja2 blocks")
    print("                   Blocks: head, sidebar, main_intro, main_first,")
    print("                            main_second, main_third, main_cta, footer")
    print("                   Preserves: #intro, #first, #second, #third, #cta, #spacer")
    print()
    print("timeline.html     - Extracted #fourth section (lines 327-380)")
    print("                   Contains: 9 activity timeline entries")
    print("                   Purpose: Rendered via Python template engine")
    print()
    print("cron.html         - Extracted #fifth section (lines 383-417)")
    print("                   Contains: 6 cron job entries with status")
    print("                   Purpose: Rendered via Python template engine")
    print()
    print("heatmap.html      - NEW sub-section for #fourth")
    print("                   Purpose: GitHub-style contribution heatmap")
    print()
    print("stats.html        - NEW sub-section for #fourth")
    print("                   Purpose: Activity statistics summary")
    print()
    print("-" * 70)
    print("STATIC sections → base.html ({% block %} pairs)")
    print("DYNAMIC sections → Python renders into {% block main_fourth %} etc.")
    print("-" * 70)
    print()

    # ─── SIDEBAR NAV STRUCTURE ────────────────────────────────────────────────
    print("🔗 NAVIGATION HASH LINKS")
    print("-" * 70)
    nav_map = {
        "#intro":   "소개",
        "#first":   "에이전트 헤르",
        "#second":  "사용자 정보",
        "#third":   "메모리 시스템",
        "#fourth":  "활동 타임라인",
        "#fifth":   "크론 작업",
    }
    for href, label in nav_map.items():
        print(f"  {href} → {label}")
    print()
    print("=" * 70)
    print("ANALYSIS COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    analyze_html()
